---
- name: "Choose task based on platform"
  include_tasks: "{{ platform }}"
  with_first_found:
    - "system/{{ ansible_os_family }}.yml"
    - "system/not-supported.yml"
  loop_control:
    loop_var: platform

- name: "Setup npm and install global packages"
  include_tasks: "npm.yml"
  when: npm_global_user | trim and npm_global_group | trim
