---
- block:
    - name: "Make sure npm group exists"
      group:
        name: '{{ npm_global_group }}'
        state: present

    - name: "Make sure npm user exists"
      user:
        name: '{{ npm_global_user }}'
        group: '{{ npm_global_group }}'
        state: present

    - name: "Create npm global directory"
      file:
        path: '{{ npm_global_directory }}'
        owner: '{{ npm_global_user }}'
        group: '{{ npm_global_group }}'
        state: directory

    - name: "Add npm global directory to $PATH"
      template:
        src: npm.sh.j2
        dest: /etc/profile.d/npm.sh
        mode: 0644

    - name: "Install npm global packages"
      become: True
      become_user: '{{ npm_global_user }}'
      npm:
        name: '{{ npm_global_package.name | default(npm_global_package) }}'
        version: '{{ npm_global_package.version | default("latest") }}'
        state: present
        global: True
      environment:
        NPM_CONFIG_PREFIX: '{{ npm_global_directory }}'
        NODE_PATH: '{{ npm_global_directory }}/lib/node_modules'
      loop: '{{ npm_global_packages }}'
      loop_control:
        loop_var: npm_global_package
  become: True
