---
- name: Make sure npm group exists
  become: True
  group:
    name: "{{ npm_global_group }}"
    state: present

- name: Make sure npm user exists
  become: True
  user:
    name: "{{ npm_global_user }}"
    group: "{{ npm_global_group }}"
    state: present

- name: Create npm global directory
  become: True
  file:
    path: "{{ npm_global_directory }}"
    owner: "{{ npm_global_user }}"
    group: "{{ npm_global_group }}"
    state: directory

- name: Add npm global directory to $PATH
  become: True
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644

- name: Install npm global packages
  become: True
  become_user: "{{ npm_global_user }}"
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    state: present
    global: True
  environment:
    NPM_CONFIG_PREFIX: "{{ npm_global_directory }}"
    NODE_PATH: "{{ npm_global_directory }}/lib/node_modules"
  loop: "{{ npm_global_packages }}"
