---
- name: Nodejs installation
  block:
    - name: Import nodesource RPM key
      rpm_key:
        key: '{{ nodejs_rpm_key }}'
        state: present
      register: status
      retries: 10
      delay: 2
      until: status is succeeded

    - name: Add nodesource repositories
      package:
        name: '{{ nodejs_yum_url }}'
        state: present
      register: status
      retries: 10
      delay: 2
      until: status is succeeded

    - name: Install node.js and npm
      yum:
        name: 'nodejs-{{ nodejs_version }}'
        enablerepo: nodesource
        state: present
      register: status
      retries: 10
      delay: 2
      until: status is succeeded

    - name: Install build tools
      package:
        name:
          - gcc-c++
          - make
        state: present
      register: status
      retries: 10
      delay: 2
      until: status is succeeded
      when: build_tools
  become: True
