---
- name: Define transport
  set_fact:
    nodejs_transport: >-
      {{ ansible_distribution_major_version is version('7', '<')
        | ternary('http','https') }}

- block:
    - name: Import nodesource RPM key
      rpm_key:
        key: "{{ nodejs_transport }}://rpm.nodesource.com/pub/el/\
              NODESOURCE-GPG-SIGNING-KEY-EL"
        state: present
      register: status
      retries: 10
      delay: 2
      until: status is succeeded

    - name: Add nodesource repositories
      package:
        name: "{{ nodejs_transport }}://rpm.nodesource.com/pub_{{ nodejs_version }}\
              .x/el/{{ ansible_distribution_major_version }}/\
              {{ ansible_architecture }}/nodesource-release-el\
              {{ ansible_distribution_major_version }}-1.noarch.rpm"
        state: present
      register: status
      retries: 10
      delay: 2
      until: status is succeeded

    - name: Install node.js and npm
      yum:
        name: "nodejs-{{ nodejs_version }}.*"
        enablerepo: nodesource
        state: present
      register: status
      retries: 10
      delay: 2
      until: status is succeeded

    - name: Install build tools
      package:
        name:
          - gcc-c++
          - make
        state: present
      register: status
      retries: 10
      delay: 2
      until: status is succeeded
      when: build_tools
  become: True
