---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-nodejs
    image: ami-9887c6e7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

  - name: test-aws-centos6-nodejs
    image: ami-1585c46a
    instance_type: m4.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
     - rhel_family

  - name: test-aws-ubuntu16-nodejs
    image: ami-09677e0a6b14905b0
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family

  - name: test-aws-ubuntu18-nodejs
    image: ami-012fd5eb46f56731f
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family

provisioner:
  name: ansible
  log: False
  inventory:
    group_vars:
      rhel_family:
        nodejs_version: 10.15.3
      debian_family:
        nodejs_version: 10*
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/provisioning/AWS/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-direct
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
