---
- name: Converge
  hosts: all

  vars:
    nodejs_branch: 10
    build_tools: true
    npm_global_user: me
    npm_global_group: me
    npm_global_directory: /home/me/.local
    npm_global_packages:
      - name: jslint
        version: 0.12.0
      - name: validator

  roles:
    - role: ansible-role-nodejs
